<?php
/**
 * Core SEO/GEO plugin for Craft CMS
 *
 * A no fluff SEO/GEO solution for Craft CMS websites.
 *
 * @link      https://digitalastronaut.be
 * @copyright Copyright (c) 2026 Digitalastronaut
 */

namespace digitalastronaut\craftcoreseogeo\console\controllers;

use craft\console\Controller;
use craft\helpers\FileHelper;
use craft\helpers\Json;

use yii\console\ExitCode;
use yii\helpers\Console;

/**
 * Compiles the vendored schema.org CSV release (`src/static/schemaorg/`) into
 * `registry.php` - a flat, inheritance-resolved lookup of every pickable
 * schema.org type and its properties, used to drive the structured data type
 * picker and property-mapping UI.
 *
 * Also writes `registry.json`, the same data for `web\assets\schema\SchemaAssetBundle` to
 * publish as a static CP resource - PHP reads `registry.php` directly (no decode cost), CP JS
 * fetches `registry.json`. Both are written from the same in-memory array in this one command
 * run, so they can't drift out of sync with each other.
 *
 * @author      Digitalastronaut
 * @package     CoreSeoGeo
 * @since       v1.0.0
 */
class SchemaController extends Controller {
    private const SCHEMA_ORG_URI_PREFIX = 'https://schema.org/';

    /**
     * Compiles `schemaorg-current-https-types.csv` and
     * `schemaorg-current-https-properties.csv` into `registry.php`, right
     * next to the source files. Re-run this after vendoring a newer
     * schema.org release.
     *
     * @return int
     *
     * @author      Digitalastronaut
     * @since       v1.0.0
     */
    public function actionGenerate(): int {
        $dir = dirname(__DIR__, 2) . '/static/schemaorg';
        $typesCsv = $dir . '/schemaorg-current-https-types.csv';
        $propertiesCsv = $dir . '/schemaorg-current-https-properties.csv';

        if (!is_file($typesCsv) || !is_file($propertiesCsv)) {
            $this->stderr("Vendored schema.org CSV files not found in {$dir}" . PHP_EOL, Console::FG_RED);
            return ExitCode::UNSPECIFIED_ERROR;
        }

        $properties = $this->parseProperties($propertiesCsv);
        $types = $this->parseTypes($typesCsv, $properties);

        $this->warnAboutDanglingReferences($types, $properties);

        // Property definitions (description, expectedTypes) are stored once here, keyed by
        // name - a type's own entry only lists which property *names* apply to it. Properties
        // like "name"/"description" are shared by hundreds of types; inlining full definitions
        // per type (the first version of this generator did) bloated the compiled file to
        // ~20MB and ~107MB once loaded into memory, almost all of it duplicated text.
        ksort($properties);
        ksort($types);

        $registry = [
            'properties' => $properties,
            'types' => $types,
        ];

        $export = var_export($registry, true);
        $php = <<<PHP
        <?php
        /**
         * Generated by `php craft core-seo-geo/schema/generate` - do not edit by hand.
         * Source: schema.org (current, https) - see VERSION.md for the pinned release.
         */

        return {$export};

        PHP;

        FileHelper::writeToFile($dir . '/registry.php', $php);
        FileHelper::writeToFile(
            $dir . '/registry.json',
            Json::encode($registry, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
        );

        $this->stdout('Generated registry.php and registry.json with ' . count($types) . ' types and ' . count($properties) . ' properties.' . PHP_EOL, Console::FG_GREEN);

        return ExitCode::OK;
    }

    /**
     * Properties whose own `supersededBy` is set are dropped entirely here (not just hidden
     * per-type) - schema.org has already named their replacement, so nothing should reference
     * the old name.
     *
     * @param string $path
     * @return array<string, array{description: string, expectedTypes: string[]}>
     */
    private function parseProperties(string $path): array {
        $properties = [];

        foreach ($this->readCsv($path) as $row) {
            if ($row['supersededBy'] !== '') continue;

            $name = $this->shortName($row['id']);
            if ($name === null) continue;

            $properties[$name] = [
                'description' => $this->absolutizeLinks(trim($row['comment'])),
                'expectedTypes' => $this->splitNames($row['rangeIncludes']),
            ];
        }

        return $properties;
    }

    /**
     * @param string $path
     * @param array<string, array{description: string, expectedTypes: string[]}> $properties
     * @return array<string, array{label: string, description: string, parentTypes: string[], properties: string[]}>
     */
    private function parseTypes(string $path, array $properties): array {
        $types = [];

        foreach ($this->readCsv($path) as $row) {
            // Enumeration *member* rows (e.g. "Friday") carry the enum class they belong to
            // here; they're values, not types a user should ever pick as a root object.
            if ($row['enumerationtype'] !== '') continue;

            $name = $this->shortName($row['id']);
            if ($name === null) continue;

            $typeProperties = array_values(array_filter(
                $this->splitNames($row['properties']),
                fn(string $propertyName): bool => isset($properties[$propertyName]),
            ));
            sort($typeProperties);

            $types[$name] = [
                'label' => $row['label'],
                'description' => $this->absolutizeLinks(trim($row['comment'])),
                'parentTypes' => $this->splitNames($row['subTypeOf']),
                'properties' => $typeProperties,
            ];
        }

        return $types;
    }

    /**
     * Diagnostic only - a property's `rangeIncludes` naming a type that isn't in our filtered
     * set would otherwise fail silently in the mapping UI later.
     *
     * @param array<string, array{properties: string[]}> $types
     * @param array<string, array{expectedTypes: string[]}> $properties
     * @return void
     */
    private function warnAboutDanglingReferences(array $types, array $properties): void {
        foreach ($types as $typeName => $type) {
            foreach ($type['properties'] as $propertyName) {
                foreach ($properties[$propertyName]['expectedTypes'] as $expectedType) {
                    if (!isset($types[$expectedType])) {
                        $this->stdout(
                            "Warning: {$typeName}.{$propertyName} references unknown type \"{$expectedType}\"" . PHP_EOL,
                            Console::FG_YELLOW,
                        );
                    }
                }
            }
        }
    }

    /**
     * @param string $path
     * @return \Generator<array<string, string>>
     */
    private function readCsv(string $path): \Generator {
        $handle = fopen($path, 'rb');

        $header = fgetcsv($handle);
        $header = array_map('trim', $header);

        while (($row = fgetcsv($handle)) !== false) {
            if (count($row) !== count($header)) continue;
            yield array_combine($header, $row);
        }

        fclose($handle);
    }

    /**
     * @param string $value Comma-separated schema.org URIs.
     * @return string[]
     */
    private function splitNames(string $value): array {
        if ($value === '') return [];

        $names = [];

        foreach (explode(',', $value) as $uri) {
            $name = $this->shortName(trim($uri));
            if ($name !== null) $names[] = $name;
        }

        return $names;
    }

    /**
     * @param string $uri
     * @return string|null The local type/property name, or null for a non-schema.org URI
     * (e.g. a `subTypeOf` pointing at a bare RDFS class).
     */
    private function shortName(string $uri): ?string {
        if (!str_starts_with($uri, self::SCHEMA_ORG_URI_PREFIX)) return null;
        return substr($uri, strlen(self::SCHEMA_ORG_URI_PREFIX));
    }

    /**
     * `comment` text links to other vocabulary terms and doc pages with a bare relative href
     * (`href="/EmployerReview"`, `href="/docs/datamodel.html#..."`) - correct only when hosted
     * on schema.org itself. Verified against every `<a>` tag in both vendored CSVs: every
     * relative href is meant to resolve against schema.org, and no absolute href (Wikipedia,
     * W3C, etc.) ever starts with "/", so this has no false positives.
     *
     * @param string $comment
     * @return string
     */
    private function absolutizeLinks(string $comment): string {
        return preg_replace('/href="\//', 'href="' . self::SCHEMA_ORG_URI_PREFIX, $comment);
    }
}
